GATSBY_SITE=devhub
GATSBY_PARSER_USER=jordanstapinski
GATSBY_PARSER_CI_USER=jordanstapinski
GATSBY_PARSER_BRANCH=CI
GATSBY_SNOOTY_DEV=true
PREVIEW_MODE=true
STRAPI_URL=http://18.144.177.6:1337
STRAPI_PUBLICATION_STATE=live