# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: DevHub npm test

on:
    pull_request:
        branches: [master, staging]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout target branch
              uses: actions/checkout@v2
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Cache Packages
              uses: bahmutov/npm-install@v1
            - run: npm test
